# ** CONFIGURACIONES CAMARA
camara:
  indice: 0 
  backend: "any" # Backend de OpenCV (any, v4l2, gstreamer)
  # ** CUADRO DE IMAGEN 
  resolucion: 
    ancho: 640
    alto: 480

  fps: 30

  brillo: 0
  contraste: 0
  saturacion: 0
  exposicion: -1
# ** CONFIGURACION DE RASPBY
raspberry_pi:
  usar_picamera: false       # true para usar picamera2
  buffer_size: 1             # Tamaño del buffer (menor = menos latencia)
  flip_horizontal: false     # Voltear imagen horizontalmente
  flip_vertical: false       # Voltear imagen verticalmente

  capturas: 
    guardar_automatico: false
    ruta: "assets/images/"
    formato: "jpg"
    calidad: 85
    incluir_timestamp: true  # fecha y hora de la cap
# *** DETECCION DE OBJETOS 
deteccion_objetos: 
  activa: true         # activar/desactivar detección de objetos
  modelo: "yolov8n"   # modelo usado 
  
  confianza_minima: 0.5 
  iou_threshold: 0.4  # Threshold para Non-Maximum Suppression
  max_detecciones: 10 # detecciones max por frame
  # Clases importantes para personas con discapacidad visual
  clases_prioritarias:
    # Obstaculos
    - "person"                 
    - "bicycle"               
    - "car"                   
    - "motorcycle"            
    - "bus"                   
    - "truck"                 
    - "chair"                 
    - "couch"                
    - "bed"                  
    - "dining table"          
    - "door"                 
    - "stairs"               
    # Objetos cotidianos importantes
    - "bottle"               
    - "cup"                   
    - "fork"                 
    - "knife"                
    - "spoon"                 
    - "bowl"                  
    - "book"                  
    - "laptop"                
    - "cell phone"            
    - "remote"                
    - "keyboard"              
    - "mouse"                
    # Electrodomésticos
    - "microwave"             
    - "oven"                  
    - "toaster"               
    - "sink"                 
    - "refrigerator"          
    - "tv"                    
  # Traducción de nombres de clases al español
  traducciones:
    "person": "persona"
    "bicycle": "bicicleta" 
    "car": "automóvil"
    "motorcycle": "motocicleta"
    "airplane": "avión"
    "bus": "autobús"
    "train": "tren"
    "truck": "camión"
    "boat": "barco"
    "traffic light": "semáforo"
    "fire hydrant": "hidrante"
    "stop sign": "señal de alto"
    "parking meter": "parquímetro"
    "bench": "banco"
    "bird": "pájaro"
    "cat": "gato"
    "dog": "perro"
    "horse": "caballo"
    "sheep": "oveja"
    "cow": "vaca"
    "elephant": "elefante"
    "bear": "oso"
    "zebra": "cebra"
    "giraffe": "jirafa"
    "backpack": "mochila"
    "umbrella": "paraguas"
    "handbag": "bolsa"
    "tie": "corbata"
    "suitcase": "maleta"
    "frisbee": "frisbee"
    "skis": "esquís"
    "snowboard": "tabla de nieve"
    "sports ball": "pelota deportiva"
    "kite": "cometa"
    "baseball bat": "bate de béisbol"
    "baseball glove": "guante de béisbol"
    "skateboard": "patineta"
    "surfboard": "tabla de surf"
    "tennis racket": "raqueta de tenis"
    "bottle": "botella"
    "wine glass": "copa de vino"
    "cup": "taza"
    "fork": "tenedor"
    "knife": "cuchillo"
    "spoon": "cuchara"
    "bowl": "tazón"
    "banana": "plátano"
    "apple": "manzana"
    "sandwich": "sánduwich"
    "orange": "naranja"
    "broccoli": "brócoli"
    "carrot": "zanahoria"
    "hot dog": "perro caliente"
    "pizza": "pizza"
    "donut": "dona"
    "cake": "pastel"
    "chair": "silla"
    "couch": "sofá"
    "potted plant": "planta en maceta"
    "bed": "cama"
    "dining table": "mesa de comedor"
    "toilet": "inodoro"
    "tv": "televisor"
    "laptop": "computadora portátil"
    "mouse": "ratón de computadora"
    "remote": "control remoto"
    "keyboard": "teclado"
    "cell phone": "teléfono celular"
    "microwave": "microondas"
    "oven": "horno"
    "toaster": "tostadora"
    "sink": "lavamanos"
    "refrigerator": "refrigerador"
    "book": "libro"
    "clock": "reloj"
    "vase": "florero"
    "scissors": "tijeras"
    "teddy bear": "oso de peluche"
    "hair drier": "secadora de pelo"
    "toothbrush": "cepillo de dientes"
# ** DETECCION DE PERSONAS 
deteccion_personas:
  activa: true
  metodo: "yolo"
  # HOG (más rápido, menos preciso)
  hog:
    win_stride: [8, 8]         # Paso de ventana deslizante
    padding: [32, 32]          # Padding alrededor de detecciones
    scale: 1.05                # Factor de escala entre niveles
    final_threshold: 2         # Threshold final para agrupación
    
  #  Cascada (muy rápido, básico)
  cascada:
    scale_factor: 1.1          # Factor de escala
    min_neighbors: 3           # Mínimos vecinos para detección válida
    min_size: [30, 30]         # Tamaño mínimo de detección
# ** RECONOCIMIENTO FACIAL LIBRERIA CONFIG
reconociento_facial: 
  activa: false
  rutas_caras_conocidas: src/imagen/rutas_caras_conocidas
  modelo: "hog"
  tolerancia: 0.6 
  anunciar_nombres: true      
  anunciar_desconocidos: false 
  guardar_caras_desconocidas: false 
  encriptar_datos: false     
# ** RECONOCIMIENTO DE TEXTO (OCR) LIBRERIA CONFIG
reconocimiento_texto: 
  activa: false
  idiomas: ["spa", "eng"] 
  tesseract: 
    psm: 6
    oem: 3
    config_personalizada: "--psm 6 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789áéíóúñüÁÉÍÓÚÑÜ"
  filtros: #filtros de texto
    longitud_minima: 3
    longitud_maxima: 200
    filtrar_numeros_solos: true
    filtrar_caracteres_raros: true
  procesamientno: #OCR
    escala_grises: true
    threshold_adaptativo: true
    blur_gaussiano: false
    dilatacion: false
    erosion: false
    kernel_size: 3
# ** TEXTO A VOZ (TTS) Y (GTTS)   LIBRERIA CONFIG
texto_a_voz:
  motor: "pyttsx3"
  idioma: "espanish""
  velociadad: 150
  volumen: 0.9
  voz_femenina: true
  gtts:
    idioma: "es"              
    dominio: "com.mx"         
    velocidad_lenta: false     
  intervalo_anuncios: 3.0     
  volumen_master: 0.8         
  interrumpir_anteriores: false 
  prioridades: #PRIORIDADES
    emergencia: 1              
    persona: 2                 
    obstaculo: 3              
    objeto: 4                  
    texto: 5                   
    sistema: 6
# ** INTERFAZ
interfaz:
  mostrar_video: true
  pantalla_completa: false
  redimnesionable: true
  mostrar_fps: true
  mostrar_detecciones: true
  mostrar_confianza: true 
  mostrar_nombre_clases: true 
  mostrar_cordenadad: false
  colores: 
    persona:  [0, 255, 0] #VERDE
    objeto:  [0, 255, 0] #AZUL 
    texto: [0, 0, 255]  #ROJO 
    cara_conocida:  [255, 255, 0] #CIAN
    caras_desconocidad: #AMARILLO
    fondo_texto: [0, 0, 0] #NEGRO
  fuente: 
    tipo: 1 
    escala: 0.6
    grosor: 2 
    suavizado: true 
# ** TECLAS DE CONTROL
controles: 
  salir: "q"
  ayuda: "h"
  toggle_objetos: "o"
  toggle_personas: "p"
  toggle_ocr: "t"
  toggle_caras: "f"            
  capturar_imagen: "c"
  modo_debug: "d"
  pausar_video: "space"
  pantalla_completa: "F11"
  subir_volume: "+"
  bajar_volumen: "-"
  velocidad_voz_mas: "]"
  velocidad_voz_menos: "["
# ** DEPURACION
logging:
  nivel: "INFO"   # DEBUG, INFO, WARNING, ERROR, CRITICAL
  archivo: "logs/gafas_ia.log" 
  archivo_errores: "logs/errores.log" 
  formato: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  formato_fecha: "%Y-%m-%d %H:%M:%S"
  rotacion: true             
  max_size_mb: 10              
  backup_count: 5             
  consola: true        
  colores_consola: true
# ** RENDIMIENTO
rendimiento:
  threads_deteccion: 2
  buffer_frames: 1
  raspberry_pi: #OPTIMIZACION DE RASPBY
    detectado_automaticamente: false
    u sar_gpu: false 
    reducir_resolucion: true
    resolucion_reducida: [320, 240]
    fps_reducido: 15 
    optimizar_memoria: true
  pc_desarrollo: # pc escritorio
    usar_gpu: true
    resolucion_completa: [640, 480] 
    fps_completo: 30 
    cache_modelos: true
  avanzado:
    prefetch_frames: false
    async_processing: true
    memory_pool: false
privacidad: 
  guardar_capturas: false
  guardar_audio: false
  encriptar_caras: false
  tiempo_retencion_caras: 30
  log_detecciones_personas: false
  anonimizar_logs: true
Experimental:  # Funcionalidades avanzadas (en desarrollo)
  deteccion_gestos: false
  reconocimiento_voz: false
  navegacion_indoor: false 
  deteccion_obstaculos: false
  estimacion_distancia: false
  modelo_personalizado: false #(IA)
  fine_tuning: false